#!/usr/bin/env python3
"""Run the U.S. options research pipeline once or continuously.

The service is intentionally broker-free.  It consumes the point-in-time DuckDB
research store plus provider outputs for current options/catalyst data and emits
research candidates or NO_TRADE.  The separate paper-execution seam remains the
only code path allowed to submit an Alpaca paper option order.

Examples:

  # Run the same whole-market analysis immediately.
  python scripts/run_continuous_options_analysis.py \
      --store data/options.duckdb --symbols-file data/us_symbols.json \
      --options-json data/current_options.json --force-full

  # Keep analyzing with hot-reloaded provider output files.
  python scripts/run_continuous_options_analysis.py \
      --store data/options.duckdb --symbols-file data/us_symbols.json \
      --options-json data/current_options.json \
      --catalysts-json data/current_catalysts.json --loop

For production, pass --session-calendar-json generated by an authoritative
exchange calendar/data provider.  The weekday fallback is deliberately marked
non-authoritative because it cannot know holidays or early closes.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
from pathlib import Path
import sys
import time
from typing import Any, Mapping, Sequence

ROOT = Path(__file__).resolve().parents[1]
AGENT = ROOT / "agent"
if str(AGENT) not in sys.path:
    sys.path.insert(0, str(AGENT))

from src.options_market.continuous import (  # noqa: E402
    AtomicAnalysisStateStore,
    ContinuousOptionsAnalyzer,
    ContinuousScanConfig,
    TradingSession,
    weekday_regular_session,
)
from src.options_market.store import OptionsResearchStore  # noqa: E402

UTC = timezone.utc


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Continuous U.S. options research service")
    parser.add_argument("--store", required=True, type=Path, help="Point-in-time DuckDB research store")
    parser.add_argument("--state", type=Path, default=Path("data/options-analysis-state.json"))
    parser.add_argument("--symbols-file", required=True, type=Path, help="JSON list or newline-delimited symbols")
    parser.add_argument("--options-json", type=Path, help="Hot-reloaded symbol -> option-candidate mapping")
    parser.add_argument("--catalysts-json", type=Path, help="Hot-reloaded symbol -> 0..100 catalyst score mapping")
    parser.add_argument(
        "--session-calendar-json",
        type=Path,
        help="Date-keyed session map with timezone-aware open/close timestamps",
    )
    parser.add_argument(
        "--require-authoritative-calendar",
        action="store_true",
        help="Fail instead of using the non-authoritative weekday fallback",
    )
    parser.add_argument("--loop", action="store_true", help="Continue running using phase-aware cadence")
    parser.add_argument("--force-full", action="store_true", help="Force the first cycle to scan the whole universe")
    parser.add_argument("--max-focus", type=int, default=200)
    parser.add_argument("--max-deep", type=int, default=50)
    parser.add_argument("--final-top-n", type=int, default=10)
    parser.add_argument("--target-profit-pct", type=float, default=300.0)
    parser.add_argument("--history-days", type=int, default=420)
    return parser.parse_args()


def load_symbols(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    try:
        payload = json.loads(text)
    except json.JSONDecodeError:
        payload = [line.strip() for line in text.splitlines()]
    if isinstance(payload, Mapping):
        payload = payload.get("symbols", [])
    if not isinstance(payload, Sequence) or isinstance(payload, (str, bytes)):
        raise ValueError("symbols file must be a JSON list, {symbols:[...]}, or newline-delimited file")
    return _symbols(payload)


def load_options(path: Path | None, requested: Sequence[str]) -> dict[str, list[dict[str, Any]]]:
    if path is None:
        return {}
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, Mapping):
        raise ValueError("options JSON must map symbol -> candidate list")
    wanted = set(_symbols(requested))
    output: dict[str, list[dict[str, Any]]] = {}
    for symbol, rows in payload.items():
        clean = str(symbol).strip().upper()
        if clean not in wanted or not isinstance(rows, list):
            continue
        output[clean] = [dict(row) for row in rows if isinstance(row, Mapping)]
    return output


def load_catalysts(path: Path | None, requested: Sequence[str]) -> dict[str, float]:
    if path is None:
        return {}
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, Mapping):
        raise ValueError("catalysts JSON must map symbol -> score")
    wanted = set(_symbols(requested))
    output: dict[str, float] = {}
    for symbol, value in payload.items():
        clean = str(symbol).strip().upper()
        if clean not in wanted:
            continue
        try:
            score = float(value)
        except (TypeError, ValueError, OverflowError):
            continue
        output[clean] = min(100.0, max(0.0, score))
    return output


def session_for_now(
    now: datetime,
    path: Path | None,
    *,
    require_authoritative: bool,
) -> TradingSession:
    if path is None:
        if require_authoritative:
            raise RuntimeError("--require-authoritative-calendar needs --session-calendar-json")
        return weekday_regular_session(now)

    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, Mapping):
        raise ValueError("session calendar JSON must be a date-keyed object")
    key = now.astimezone().date().isoformat()
    row = payload.get(key)
    if not isinstance(row, Mapping):
        # A missing date is treated as explicitly closed only when an
        # authoritative file was supplied; fail closed instead of inventing a
        # normal session for a holiday.
        fallback = weekday_regular_session(now)
        return TradingSession(
            open_at=fallback.open_at,
            close_at=fallback.close_at,
            trading_day=False,
            source=f"calendar:{path}",
            authoritative=True,
        )

    open_at = _aware_datetime(row.get("open"), "open")
    close_at = _aware_datetime(row.get("close"), "close")
    return TradingSession(
        open_at=open_at,
        close_at=close_at,
        trading_day=bool(row.get("trading_day", True)),
        source=str(row.get("source") or f"calendar:{path}"),
        authoritative=True,
    )


def main() -> int:
    args = parse_args()
    config = ContinuousScanConfig(
        history_days=args.history_days,
        max_focus_symbols=args.max_focus,
        max_deep_symbols=args.max_deep,
        final_top_n=args.final_top_n,
        target_profit_pct=args.target_profit_pct,
    )
    config.validate()

    store = OptionsResearchStore(args.store)
    state_store = AtomicAnalysisStateStore(args.state)

    def symbols_provider(_: datetime) -> Sequence[str]:
        # Re-read on each full scan so a separately refreshed exchange universe
        # becomes visible without restarting this service.
        return load_symbols(args.symbols_file)

    def options_provider(symbols: Sequence[str], _: datetime):
        return load_options(args.options_json, symbols)

    def catalyst_provider(symbols: Sequence[str], _: datetime):
        return load_catalysts(args.catalysts_json, symbols)

    analyzer = ContinuousOptionsAnalyzer(
        store=store,
        symbols_provider=symbols_provider,
        state_store=state_store,
        options_provider=options_provider if args.options_json else None,
        catalyst_provider=catalyst_provider if args.catalysts_json else None,
        config=config,
    )

    first = True
    try:
        while True:
            now = datetime.now(UTC)
            session = session_for_now(
                now,
                args.session_calendar_json,
                require_authoritative=args.require_authoritative_calendar,
            )
            result = analyzer.run_cycle(
                now=now,
                session=session,
                force_full=args.force_full and first,
            )
            print(json.dumps(result, indent=2, ensure_ascii=False, allow_nan=False, default=str), flush=True)
            first = False
            if not args.loop:
                break
            sleep_seconds = int(result.get("plan", {}).get("next_check_seconds", 60))
            time.sleep(max(1, sleep_seconds))
    finally:
        store.close()
    return 0


def _aware_datetime(value: object, name: str) -> datetime:
    text = str(value or "").strip()
    if not text:
        raise ValueError(f"session {name} is required")
    try:
        parsed = datetime.fromisoformat(text.replace("Z", "+00:00"))
    except ValueError as exc:
        raise ValueError(f"session {name} must be ISO-8601") from exc
    if parsed.tzinfo is None:
        raise ValueError(f"session {name} must include a timezone offset")
    return parsed


def _symbols(values: Sequence[object]) -> list[str]:
    output: list[str] = []
    seen: set[str] = set()
    for value in values:
        symbol = str(value or "").strip().upper()
        if not symbol or symbol in seen:
            continue
        seen.add(symbol)
        output.append(symbol)
    return output


if __name__ == "__main__":
    raise SystemExit(main())
